### PR TITLE
Updating Phoenix to version 0.13.1

### PR DESCRIPTION
**Pull request by omnibs**
I've updated Phoenix to current version following the update guides on `CHANGELOG.md`.

I've also ran benchmarks on Rackspace that I could include in the Repo ([here](https://gist.github.com/omnibs/e5e72b31e6bd25caf39a)). Not sure where to put it or how to name it, so I'm open to suggestions.

### CODE REVIEW

**Comment by josevalim** [comment]
Nice work @omnibs! :heart:

**Comment by mroth** [comment]
Nice!  Maybe we can add a line linking to server results in the README?  It'd be nice to add a table to it as well.

**Comment by omnibs** [comment]
Thanks =]

I've added tables, environments and server commands to the [Gist](https://gist.github.com/omnibs/e5e72b31e6bd25caf39a).

Do you think I should add a "server results" table to the README.md too besides the link to the gist?

I got scripts of what I used to create the server and client environments. They're not actual shell scripts, just lists of commands (I was lazy). I could add them on a .md to the repo. What do you think?

**Comment by zepplock** [comment]
+1 to merge this in

**Comment by mroth** [comment]
I'd leave it as a link to the gist (but perhaps bolded or something easy to notice?) so that you can continue to update the data in the future without requiring a pull request.

Sorry for the delay.  I'll merge as soon as there is an explanatory link in the README ! :-)

**Comment by omnibs** [comment]
Hey @mroth, do you think a note below the comparative benchmarks table is fine or should I make it more prominent?

I got a preview gist for it [here](https://gist.github.com/omnibs/f9b9e4bfe76d3cee2b0f)

Small pic of what I added:



Feel free to suggest better words.

**Comment by mroth** [comment]
That looks good to me, but you should feel free to add your name to the sentence to give yourself credit for making them. :-)

**Comment by omnibs** [comment]
Okay, added =]

**Pull request merged**
