### PR TITLE
Added Cuba example

### PR DESCRIPTION
**Pull request by katgironpe**
mroth/phoenix-showdown/issues/#13

### CODE REVIEW

**Comment by katgironpe** [comment]
@mroth Would be great if you benchmark this. Doesn't differ greatly from Sinatra. Thanks.

**Comment by mroth** [comment]
Thanks!  (And especially thanks for updating the setup script too!)

I'll merge this is and include the next time I do a full round of the comparative benchmarks.

**Comment by jeregrine** [comment]
Might make sense to checkout ruby-roda its a fork of cuba and in my
experience pretty great.

**Comment by katgironpe** [comment]
@jeregrine Cool. Will check it out. Cuba's maintained by a friend. Starting to learn Elixir and I guess I am pretty convinced it might be a lot better than Ruby soon.

**Comment by jeregrine** [comment]
Welcome to the community! Feel free to jump on freenode #elixir-lang or the
mailing list if you need any help!

**Comment by mroth** [comment]
I am going to merge this in advance of the next round of benchmarks to avoid merge conflicts with other submissions coming in because of the adjustment to the setup script!

**Pull request merged**
